testano possivel correcao para report

diff --git a/.github/workflows/practise7.yaml b/.github/workflows/practise7.yaml
--- a/.github/workflows/practise7.yaml
+++ b/.github/workflows/practise7.yaml
@@ -23,9 +23,10 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Cache dependencies
+        id: cache
         uses: actions/cache@v4
         with:
-          path: ~/.npm
+          path: node_modules
           key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
 
       - name: Use Node.js 20
@@ -85,6 +86,7 @@ jobs:
           done
 
       - name: Install dependencies
+        if: steps.cache.outputs.cache-hit != 'true'
         run: npm ci
 
       - name: Build project
@@ -111,20 +113,27 @@ jobs:
           echo "🚀 Executando testes e2e..."
           npm run test:e2e
 
-      # - name: Step e2e report outcome
-      #   run: echo "steps.e2e-tests.outcome=${{ steps.e2e-tests.outcome }}"
+
+      # - name: Generate report if e2e fail
+      #   id: generate-report
+       
+        # # if: steps.e2e-tests.outcome == 'failure'
+        # run: |
+        #   echo "❗ Testes e2e falharam — gerando relatório Playwright..."
+        #   npx playwright show-report --quiet
 
       - name: Upload Playwright report
+        if: env.GITHUB_ACTIONS == 'true'
         # if: steps.generate-report.outcome == 'success'
-        if: always()
+
         uses: actions/upload-artifact@v4
         with:
           name: playwright-report
           path: playwright-report
 
-      - name: Fail job if e2e failed
-        if: steps.e2e-tests.outcome == 'failure'
-        run: exit 1
+      # - name: Fail job if e2e failed
+      #   if: steps.e2e-tests.outcome == 'failure'
+      #   run: exit 1
 
   deploy:
     needs: build-and-test
